apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productcatalogue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudheergundrasi/k8s-poc.git
    targetRevision: main
    path: productcatalogue/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: productcatalogue
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
