apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-k8s-argocd-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudheergundrasi/k8s-poc.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: poc-k8s-argocd-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
