---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  type: LoadBalancer         # <-- changed to create ELB
  selector:
    app: productcatalogue
  ports:
  - protocol: TCP
    port: 80                 # <-- external port (public)
    targetPort: 8020         # <-- pod/container port
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue
spec:
  selector:
    matchLabels:
      app: productcatalogue
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - name: productcatalogue
        image: gundrasisudheer/productcatalogue:latest
        ports:
        - containerPort: 8020
        livenessProbe:              # <-- fixed port to match container
          httpGet:
            path: /healthcheck
            port: 8020
          initialDelaySeconds: 30
          timeoutSeconds: 1
