---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  labels:
    app: shopfront
spec:
  type: LoadBalancer   # <-- Change here
  selector:
    app: shopfront
  ports:
  - protocol: TCP
    port: 80            # <-- Client-facing port (standard HTTP)
    targetPort: 8010    # <-- The port on the pod (your container port)
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
spec:
  selector:
    matchLabels:
      app: shopfront
  replicas: 1
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: gundrasisudheer/shopfront:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
